dir = Dir.pwd + '/routes/'
require dir + 'root'
require dir + 'login'
require dir + 'story'
require dir + 'job'
require dir + 'client'
require dir + 'task'
require dir + 'account'
require dir + 'note'
require dir + 'user'
require dir + 'status'
require dir + 'dev'
