dir = Dir.pwd + '/models/'
require dir + 'client'
require dir + 'clientjob'
require dir + 'job'
require dir + 'task'
require dir + 'taskuser'
require dir + 'story'
require dir + 'user'
require dir + 'note'
require dir + 'invoice'
